// PROCESS...
// CUSTOMER OPENS UP THE PACKAGE FROM LAZADA
// CUSTOMER TAKES OUT PHONE TO SCAN THE QR CODE

// IF OLD CUSTOMER... ASK CUSTOMER TO LOG IN BEFORE PROCEEDING
// IF NEW CUSTOMER, ASK CUSTOMER TO SIGN UP BEFORE PROCEEDING 
